/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "hardware.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(firefly_hardware_v1_GetDeviceIdentifierRequest, firefly_hardware_v1_GetDeviceIdentifierRequest, AUTO)


PB_BIND(firefly_hardware_v1_GetDeviceIdentifierResponse, firefly_hardware_v1_GetDeviceIdentifierResponse, AUTO)


PB_BIND(firefly_hardware_v1_ConfigurePortRequest, firefly_hardware_v1_ConfigurePortRequest, AUTO)


PB_BIND(firefly_hardware_v1_ConfigurePortResponse, firefly_hardware_v1_ConfigurePortResponse, AUTO)


PB_BIND(firefly_hardware_v1_GetPortRequest, firefly_hardware_v1_GetPortRequest, AUTO)


PB_BIND(firefly_hardware_v1_GetPortResponse, firefly_hardware_v1_GetPortResponse, AUTO)


PB_BIND(firefly_hardware_v1_SetPortRequest, firefly_hardware_v1_SetPortRequest, AUTO)


PB_BIND(firefly_hardware_v1_SetPortResponse, firefly_hardware_v1_SetPortResponse, AUTO)


PB_BIND(firefly_hardware_v1_SpiChipSelect, firefly_hardware_v1_SpiChipSelect, AUTO)


PB_BIND(firefly_hardware_v1_SpiTransceiveRequest, firefly_hardware_v1_SpiTransceiveRequest, 2)


PB_BIND(firefly_hardware_v1_SpiTransceiveResponse, firefly_hardware_v1_SpiTransceiveResponse, 2)


PB_BIND(firefly_hardware_v1_I2cOperationRead, firefly_hardware_v1_I2cOperationRead, AUTO)


PB_BIND(firefly_hardware_v1_I2cResultRead, firefly_hardware_v1_I2cResultRead, AUTO)


PB_BIND(firefly_hardware_v1_I2cOperationWrite, firefly_hardware_v1_I2cOperationWrite, AUTO)


PB_BIND(firefly_hardware_v1_I2cResult, firefly_hardware_v1_I2cResult, AUTO)


PB_BIND(firefly_hardware_v1_I2cOperation, firefly_hardware_v1_I2cOperation, AUTO)


PB_BIND(firefly_hardware_v1_I2cTransferRequest, firefly_hardware_v1_I2cTransferRequest, 2)


PB_BIND(firefly_hardware_v1_I2cTransferResponse, firefly_hardware_v1_I2cTransferResponse, 2)



