/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_FIREFLY_OPTIONS_V1_OPTIONS_PB_H_INCLUDED
#define PB_FIREFLY_OPTIONS_V1_OPTIONS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Extensions */
extern const pb_extension_type_t firefly_options_v1_c_prefix; /* field type: pb_callback_t c_prefix; */
extern const pb_extension_type_t firefly_options_v1_python_prefix; /* field type: pb_callback_t python_prefix; */
extern const pb_extension_type_t firefly_options_v1_package_id; /* field type: uint32_t package_id; */
extern const pb_extension_type_t firefly_options_v1_service_id; /* field type: uint32_t service_id; */
extern const pb_extension_type_t firefly_options_v1_method_id; /* field type: uint32_t method_id; */
extern const pb_extension_type_t firefly_options_v1_access; /* field type: uint32_t access; */

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
