/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_FIREFLY_RTC_V1_RTC_PB_H_INCLUDED
#define PB_FIREFLY_RTC_V1_RTC_PB_H_INCLUDED
#include <pb.h>
#include "options.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _firefly_rtc_v1_DisplayFormat { 
    firefly_rtc_v1_DisplayFormat_Use12HourClock = 0, 
    firefly_rtc_v1_DisplayFormat_Use24HourClock = 1 
} firefly_rtc_v1_DisplayFormat;

/* Struct definitions */
typedef struct _firefly_rtc_v1_GetConfigurationRequest { 
    char dummy_field;
} firefly_rtc_v1_GetConfigurationRequest;

typedef struct _firefly_rtc_v1_GetTimeRequest { 
    char dummy_field;
} firefly_rtc_v1_GetTimeRequest;

typedef struct _firefly_rtc_v1_SetConfigurationResponse { 
    char dummy_field;
} firefly_rtc_v1_SetConfigurationResponse;

typedef struct _firefly_rtc_v1_SetTimeResponse { 
    char dummy_field;
} firefly_rtc_v1_SetTimeResponse;

typedef struct _firefly_rtc_v1_Configuration { 
    int32_t time_zone_offset;
    firefly_rtc_v1_DisplayFormat display_format;
} firefly_rtc_v1_Configuration;

typedef struct _firefly_rtc_v1_GetTimeResponse { 
    bool is_set;
    int64_t utc;
    int32_t us;
} firefly_rtc_v1_GetTimeResponse;

typedef struct _firefly_rtc_v1_SetTimeRequest { 
    int64_t utc;
    int32_t us;
} firefly_rtc_v1_SetTimeRequest;

typedef struct _firefly_rtc_v1_GetConfigurationResponse { 
    bool has_configuration;
    firefly_rtc_v1_Configuration configuration;
} firefly_rtc_v1_GetConfigurationResponse;

typedef struct _firefly_rtc_v1_SetConfigurationRequest { 
    bool has_configuration;
    firefly_rtc_v1_Configuration configuration;
} firefly_rtc_v1_SetConfigurationRequest;


/* Helper constants for enums */
#define _firefly_rtc_v1_DisplayFormat_MIN firefly_rtc_v1_DisplayFormat_Use12HourClock
#define _firefly_rtc_v1_DisplayFormat_MAX firefly_rtc_v1_DisplayFormat_Use24HourClock
#define _firefly_rtc_v1_DisplayFormat_ARRAYSIZE ((firefly_rtc_v1_DisplayFormat)(firefly_rtc_v1_DisplayFormat_Use24HourClock+1))


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define firefly_rtc_v1_GetTimeRequest_init_default {0}
#define firefly_rtc_v1_GetTimeResponse_init_default {0, 0, 0}
#define firefly_rtc_v1_SetTimeRequest_init_default {0, 0}
#define firefly_rtc_v1_SetTimeResponse_init_default {0}
#define firefly_rtc_v1_Configuration_init_default {0, _firefly_rtc_v1_DisplayFormat_MIN}
#define firefly_rtc_v1_GetConfigurationRequest_init_default {0}
#define firefly_rtc_v1_GetConfigurationResponse_init_default {false, firefly_rtc_v1_Configuration_init_default}
#define firefly_rtc_v1_SetConfigurationRequest_init_default {false, firefly_rtc_v1_Configuration_init_default}
#define firefly_rtc_v1_SetConfigurationResponse_init_default {0}
#define firefly_rtc_v1_GetTimeRequest_init_zero  {0}
#define firefly_rtc_v1_GetTimeResponse_init_zero {0, 0, 0}
#define firefly_rtc_v1_SetTimeRequest_init_zero  {0, 0}
#define firefly_rtc_v1_SetTimeResponse_init_zero {0}
#define firefly_rtc_v1_Configuration_init_zero   {0, _firefly_rtc_v1_DisplayFormat_MIN}
#define firefly_rtc_v1_GetConfigurationRequest_init_zero {0}
#define firefly_rtc_v1_GetConfigurationResponse_init_zero {false, firefly_rtc_v1_Configuration_init_zero}
#define firefly_rtc_v1_SetConfigurationRequest_init_zero {false, firefly_rtc_v1_Configuration_init_zero}
#define firefly_rtc_v1_SetConfigurationResponse_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define firefly_rtc_v1_Configuration_time_zone_offset_tag 1
#define firefly_rtc_v1_Configuration_display_format_tag 2
#define firefly_rtc_v1_GetTimeResponse_is_set_tag 1
#define firefly_rtc_v1_GetTimeResponse_utc_tag   2
#define firefly_rtc_v1_GetTimeResponse_us_tag    3
#define firefly_rtc_v1_SetTimeRequest_utc_tag    2
#define firefly_rtc_v1_SetTimeRequest_us_tag     3
#define firefly_rtc_v1_GetConfigurationResponse_configuration_tag 1
#define firefly_rtc_v1_SetConfigurationRequest_configuration_tag 1

/* Struct field encoding specification for nanopb */
#define firefly_rtc_v1_GetTimeRequest_FIELDLIST(X, a) \

#define firefly_rtc_v1_GetTimeRequest_CALLBACK NULL
#define firefly_rtc_v1_GetTimeRequest_DEFAULT NULL

#define firefly_rtc_v1_GetTimeResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     is_set,            1) \
X(a, STATIC,   SINGULAR, SINT64,   utc,               2) \
X(a, STATIC,   SINGULAR, SINT32,   us,                3)
#define firefly_rtc_v1_GetTimeResponse_CALLBACK NULL
#define firefly_rtc_v1_GetTimeResponse_DEFAULT NULL

#define firefly_rtc_v1_SetTimeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT64,   utc,               2) \
X(a, STATIC,   SINGULAR, SINT32,   us,                3)
#define firefly_rtc_v1_SetTimeRequest_CALLBACK NULL
#define firefly_rtc_v1_SetTimeRequest_DEFAULT NULL

#define firefly_rtc_v1_SetTimeResponse_FIELDLIST(X, a) \

#define firefly_rtc_v1_SetTimeResponse_CALLBACK NULL
#define firefly_rtc_v1_SetTimeResponse_DEFAULT NULL

#define firefly_rtc_v1_Configuration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   time_zone_offset,   1) \
X(a, STATIC,   SINGULAR, UENUM,    display_format,    2)
#define firefly_rtc_v1_Configuration_CALLBACK NULL
#define firefly_rtc_v1_Configuration_DEFAULT NULL

#define firefly_rtc_v1_GetConfigurationRequest_FIELDLIST(X, a) \

#define firefly_rtc_v1_GetConfigurationRequest_CALLBACK NULL
#define firefly_rtc_v1_GetConfigurationRequest_DEFAULT NULL

#define firefly_rtc_v1_GetConfigurationResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  configuration,     1)
#define firefly_rtc_v1_GetConfigurationResponse_CALLBACK NULL
#define firefly_rtc_v1_GetConfigurationResponse_DEFAULT NULL
#define firefly_rtc_v1_GetConfigurationResponse_configuration_MSGTYPE firefly_rtc_v1_Configuration

#define firefly_rtc_v1_SetConfigurationRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  configuration,     1)
#define firefly_rtc_v1_SetConfigurationRequest_CALLBACK NULL
#define firefly_rtc_v1_SetConfigurationRequest_DEFAULT NULL
#define firefly_rtc_v1_SetConfigurationRequest_configuration_MSGTYPE firefly_rtc_v1_Configuration

#define firefly_rtc_v1_SetConfigurationResponse_FIELDLIST(X, a) \

#define firefly_rtc_v1_SetConfigurationResponse_CALLBACK NULL
#define firefly_rtc_v1_SetConfigurationResponse_DEFAULT NULL

extern const pb_msgdesc_t firefly_rtc_v1_GetTimeRequest_msg;
extern const pb_msgdesc_t firefly_rtc_v1_GetTimeResponse_msg;
extern const pb_msgdesc_t firefly_rtc_v1_SetTimeRequest_msg;
extern const pb_msgdesc_t firefly_rtc_v1_SetTimeResponse_msg;
extern const pb_msgdesc_t firefly_rtc_v1_Configuration_msg;
extern const pb_msgdesc_t firefly_rtc_v1_GetConfigurationRequest_msg;
extern const pb_msgdesc_t firefly_rtc_v1_GetConfigurationResponse_msg;
extern const pb_msgdesc_t firefly_rtc_v1_SetConfigurationRequest_msg;
extern const pb_msgdesc_t firefly_rtc_v1_SetConfigurationResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define firefly_rtc_v1_GetTimeRequest_fields &firefly_rtc_v1_GetTimeRequest_msg
#define firefly_rtc_v1_GetTimeResponse_fields &firefly_rtc_v1_GetTimeResponse_msg
#define firefly_rtc_v1_SetTimeRequest_fields &firefly_rtc_v1_SetTimeRequest_msg
#define firefly_rtc_v1_SetTimeResponse_fields &firefly_rtc_v1_SetTimeResponse_msg
#define firefly_rtc_v1_Configuration_fields &firefly_rtc_v1_Configuration_msg
#define firefly_rtc_v1_GetConfigurationRequest_fields &firefly_rtc_v1_GetConfigurationRequest_msg
#define firefly_rtc_v1_GetConfigurationResponse_fields &firefly_rtc_v1_GetConfigurationResponse_msg
#define firefly_rtc_v1_SetConfigurationRequest_fields &firefly_rtc_v1_SetConfigurationRequest_msg
#define firefly_rtc_v1_SetConfigurationResponse_fields &firefly_rtc_v1_SetConfigurationResponse_msg

/* Maximum encoded size of messages (where known) */
#define firefly_rtc_v1_Configuration_size        8
#define firefly_rtc_v1_GetConfigurationRequest_size 0
#define firefly_rtc_v1_GetConfigurationResponse_size 10
#define firefly_rtc_v1_GetTimeRequest_size       0
#define firefly_rtc_v1_GetTimeResponse_size      19
#define firefly_rtc_v1_SetConfigurationRequest_size 10
#define firefly_rtc_v1_SetConfigurationResponse_size 0
#define firefly_rtc_v1_SetTimeRequest_size       17
#define firefly_rtc_v1_SetTimeResponse_size      0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
