/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "rtc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(firefly_rtc_v1_GetTimeRequest, firefly_rtc_v1_GetTimeRequest, AUTO)


PB_BIND(firefly_rtc_v1_GetTimeResponse, firefly_rtc_v1_GetTimeResponse, AUTO)


PB_BIND(firefly_rtc_v1_SetTimeRequest, firefly_rtc_v1_SetTimeRequest, AUTO)


PB_BIND(firefly_rtc_v1_SetTimeResponse, firefly_rtc_v1_SetTimeResponse, AUTO)


PB_BIND(firefly_rtc_v1_Configuration, firefly_rtc_v1_Configuration, AUTO)


PB_BIND(firefly_rtc_v1_GetConfigurationRequest, firefly_rtc_v1_GetConfigurationRequest, AUTO)


PB_BIND(firefly_rtc_v1_GetConfigurationResponse, firefly_rtc_v1_GetConfigurationResponse, AUTO)


PB_BIND(firefly_rtc_v1_SetConfigurationRequest, firefly_rtc_v1_SetConfigurationRequest, AUTO)


PB_BIND(firefly_rtc_v1_SetConfigurationResponse, firefly_rtc_v1_SetConfigurationResponse, AUTO)




