/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "stream.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(firefly_stream_v1_Value, firefly_stream_v1_Value, AUTO)


PB_BIND(firefly_stream_v1_ConnectionConfiguration, firefly_stream_v1_ConnectionConfiguration, AUTO)



