/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.6 */

#ifndef PB_FIREFLY_UX_V1_UX_PB_H_INCLUDED
#define PB_FIREFLY_UX_V1_UX_PB_H_INCLUDED
#include <pb.h>
#include "options.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _firefly_ux_v1_Completed { 
    char dummy_field;
} firefly_ux_v1_Completed;

typedef struct _firefly_ux_v1_SendInputEventsResponse { 
    char dummy_field;
} firefly_ux_v1_SendInputEventsResponse;

typedef struct _firefly_ux_v1_SetDisplayConfigurationResponse { 
    char dummy_field;
} firefly_ux_v1_SetDisplayConfigurationResponse;

typedef struct _firefly_ux_v1_SetInteractionConfigurationResponse { 
    char dummy_field;
} firefly_ux_v1_SetInteractionConfigurationResponse;

typedef struct _firefly_ux_v1_SetScreenResponse { 
    char dummy_field;
} firefly_ux_v1_SetScreenResponse;

typedef struct _firefly_ux_v1_SetUpdateEnabledResponse { 
    char dummy_field;
} firefly_ux_v1_SetUpdateEnabledResponse;

typedef struct _firefly_ux_v1_UpdateResponse { 
    char dummy_field;
} firefly_ux_v1_UpdateResponse;

typedef struct _firefly_ux_v1_Area { 
    int32_t x;
    int32_t y;
    int32_t width;
    int32_t height;
} firefly_ux_v1_Area;

typedef struct _firefly_ux_v1_ButtonCondition { 
    uint32_t gesture;
    uint32_t button;
} firefly_ux_v1_ButtonCondition;

typedef struct _firefly_ux_v1_ButtonEvent { 
    uint32_t gesture; /* none: 0, click: 5 */
    uint32_t action; /* release: 0, pressed: 1 */
    uint32_t button;
} firefly_ux_v1_ButtonEvent;

typedef struct _firefly_ux_v1_ColorFrameBuffer { 
    uint32_t r;
    uint32_t g;
    uint32_t b;
} firefly_ux_v1_ColorFrameBuffer;

typedef struct _firefly_ux_v1_DisplayConfiguration { 
    uint32_t timeout;
} firefly_ux_v1_DisplayConfiguration;

typedef PB_BYTES_ARRAY_T(256) firefly_ux_v1_FrameBufferRead_data_t;
typedef struct _firefly_ux_v1_FrameBufferRead { 
    firefly_ux_v1_FrameBufferRead_data_t data;
} firefly_ux_v1_FrameBufferRead;

typedef struct _firefly_ux_v1_FunctionOperation { 
    uint32_t function_identifier;
} firefly_ux_v1_FunctionOperation;

typedef struct _firefly_ux_v1_GetDisplayConfigurationRequest { 
    uint32_t user_interface_identifier;
} firefly_ux_v1_GetDisplayConfigurationRequest;

typedef struct _firefly_ux_v1_GetDisplayMetadataRequest { 
    uint32_t user_interface_identifier;
} firefly_ux_v1_GetDisplayMetadataRequest;

typedef struct _firefly_ux_v1_GetInteractionConfigurationRequest { 
    uint32_t user_interface_identifier;
} firefly_ux_v1_GetInteractionConfigurationRequest;

typedef struct _firefly_ux_v1_GetScreenRequest { 
    uint32_t user_interface_identifier;
} firefly_ux_v1_GetScreenRequest;

typedef struct _firefly_ux_v1_GetScreenResponse { 
    uint32_t screen_identifier;
} firefly_ux_v1_GetScreenResponse;

typedef struct _firefly_ux_v1_GetUpdateEnabledRequest { 
    uint32_t user_interface_identifier;
} firefly_ux_v1_GetUpdateEnabledRequest;

typedef struct _firefly_ux_v1_GetUpdateEnabledResponse { 
    bool enabled;
} firefly_ux_v1_GetUpdateEnabledResponse;

typedef struct _firefly_ux_v1_GrayFrameBuffer { 
    uint32_t depth;
} firefly_ux_v1_GrayFrameBuffer;

typedef struct _firefly_ux_v1_NavigateOperation { 
    uint32_t screen_identifier;
} firefly_ux_v1_NavigateOperation;

typedef struct _firefly_ux_v1_Point { 
    int32_t x;
    int32_t y;
} firefly_ux_v1_Point;

typedef struct _firefly_ux_v1_SetScreenRequest { 
    uint32_t user_interface_identifier;
    uint32_t screen_identifier;
} firefly_ux_v1_SetScreenRequest;

typedef struct _firefly_ux_v1_SetUpdateEnabledRequest { 
    uint32_t user_interface_identifier;
    bool enabled;
} firefly_ux_v1_SetUpdateEnabledRequest;

typedef struct _firefly_ux_v1_TouchEvent { 
    uint32_t gesture; /* none: 0, slide up: 1, slide down: 2, slide left: 3, slide right: 4, click: 5, double click: 11, press: 12 */
    uint32_t action; /* release: 0, pressed: 1 */
    int32_t x;
    int32_t y;
} firefly_ux_v1_TouchEvent;

typedef struct _firefly_ux_v1_UpdateRequest { 
    uint32_t user_interface_identifier;
} firefly_ux_v1_UpdateRequest;

typedef struct _firefly_ux_v1_FrameBufferReadRequest { 
    uint32_t user_interface_identifier;
    bool has_area;
    firefly_ux_v1_Area area;
} firefly_ux_v1_FrameBufferReadRequest;

typedef struct _firefly_ux_v1_FrameBufferReadResponse { 
    pb_size_t which_message;
    union {
        firefly_ux_v1_FrameBufferRead read;
        firefly_ux_v1_Completed completed;
    } message;
} firefly_ux_v1_FrameBufferReadResponse;

typedef struct _firefly_ux_v1_GetDisplayConfigurationResponse { 
    bool has_configuration;
    firefly_ux_v1_DisplayConfiguration configuration;
} firefly_ux_v1_GetDisplayConfigurationResponse;

typedef struct _firefly_ux_v1_GetDisplayMetadataResponse { 
    uint32_t width;
    uint32_t height;
    pb_size_t which_frame_buffer;
    union {
        firefly_ux_v1_ColorFrameBuffer color;
        firefly_ux_v1_GrayFrameBuffer gray;
    } frame_buffer;
} firefly_ux_v1_GetDisplayMetadataResponse;

typedef struct _firefly_ux_v1_InputEvent { 
    float delay;
    pb_size_t which_event;
    union {
        firefly_ux_v1_ButtonEvent button_event;
        firefly_ux_v1_TouchEvent touch_event;
    } event;
} firefly_ux_v1_InputEvent;

typedef struct _firefly_ux_v1_SetDisplayConfigurationRequest { 
    uint32_t user_interface_identifier;
    bool has_configuration;
    firefly_ux_v1_DisplayConfiguration configuration;
} firefly_ux_v1_SetDisplayConfigurationRequest;

typedef struct _firefly_ux_v1_TouchCondition { 
    uint32_t gesture;
    bool has_area;
    firefly_ux_v1_Area area;
} firefly_ux_v1_TouchCondition;

typedef struct _firefly_ux_v1_EventInteractionConfiguration { 
    pb_size_t which_condition;
    union {
        firefly_ux_v1_ButtonCondition button_condition;
        firefly_ux_v1_TouchCondition touch_condition;
    } condition;
    pb_size_t which_operation;
    union {
        firefly_ux_v1_NavigateOperation navigate_operation;
        firefly_ux_v1_FunctionOperation function_operation;
    } operation;
} firefly_ux_v1_EventInteractionConfiguration;

typedef struct _firefly_ux_v1_SendInputEventsRequest { 
    uint32_t user_interface_identifier;
    pb_size_t input_events_count;
    firefly_ux_v1_InputEvent input_events[8];
} firefly_ux_v1_SendInputEventsRequest;

typedef struct _firefly_ux_v1_ScreenInteractionConfiguration { 
    uint32_t screen_identifier;
    pb_size_t event_interaction_configurations_count;
    firefly_ux_v1_EventInteractionConfiguration event_interaction_configurations[4];
} firefly_ux_v1_ScreenInteractionConfiguration;

typedef struct _firefly_ux_v1_InteractionConfiguration { 
    pb_size_t screen_interaction_configurations_count;
    firefly_ux_v1_ScreenInteractionConfiguration screen_interaction_configurations[32];
} firefly_ux_v1_InteractionConfiguration;

typedef struct _firefly_ux_v1_GetInteractionConfigurationResponse { 
    bool has_configuration;
    firefly_ux_v1_InteractionConfiguration configuration;
} firefly_ux_v1_GetInteractionConfigurationResponse;

typedef struct _firefly_ux_v1_SetInteractionConfigurationRequest { 
    uint32_t user_interface_identifier;
    bool has_configuration;
    firefly_ux_v1_InteractionConfiguration configuration;
} firefly_ux_v1_SetInteractionConfigurationRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define firefly_ux_v1_Completed_init_default     {0}
#define firefly_ux_v1_Point_init_default         {0, 0}
#define firefly_ux_v1_Area_init_default          {0, 0, 0, 0}
#define firefly_ux_v1_ColorFrameBuffer_init_default {0, 0, 0}
#define firefly_ux_v1_GrayFrameBuffer_init_default {0}
#define firefly_ux_v1_GetDisplayMetadataRequest_init_default {0}
#define firefly_ux_v1_GetDisplayMetadataResponse_init_default {0, 0, 0, {firefly_ux_v1_ColorFrameBuffer_init_default}}
#define firefly_ux_v1_FrameBufferReadRequest_init_default {0, false, firefly_ux_v1_Area_init_default}
#define firefly_ux_v1_FrameBufferRead_init_default {{0, {0}}}
#define firefly_ux_v1_FrameBufferReadResponse_init_default {0, {firefly_ux_v1_FrameBufferRead_init_default}}
#define firefly_ux_v1_GetScreenRequest_init_default {0}
#define firefly_ux_v1_GetScreenResponse_init_default {0}
#define firefly_ux_v1_SetScreenRequest_init_default {0, 0}
#define firefly_ux_v1_SetScreenResponse_init_default {0}
#define firefly_ux_v1_ButtonEvent_init_default   {0, 0, 0}
#define firefly_ux_v1_TouchEvent_init_default    {0, 0, 0, 0}
#define firefly_ux_v1_InputEvent_init_default    {0, 0, {firefly_ux_v1_ButtonEvent_init_default}}
#define firefly_ux_v1_SendInputEventsRequest_init_default {0, 0, {firefly_ux_v1_InputEvent_init_default, firefly_ux_v1_InputEvent_init_default, firefly_ux_v1_InputEvent_init_default, firefly_ux_v1_InputEvent_init_default, firefly_ux_v1_InputEvent_init_default, firefly_ux_v1_InputEvent_init_default, firefly_ux_v1_InputEvent_init_default, firefly_ux_v1_InputEvent_init_default}}
#define firefly_ux_v1_SendInputEventsResponse_init_default {0}
#define firefly_ux_v1_UpdateRequest_init_default {0}
#define firefly_ux_v1_UpdateResponse_init_default {0}
#define firefly_ux_v1_SetUpdateEnabledRequest_init_default {0, 0}
#define firefly_ux_v1_SetUpdateEnabledResponse_init_default {0}
#define firefly_ux_v1_GetUpdateEnabledRequest_init_default {0}
#define firefly_ux_v1_GetUpdateEnabledResponse_init_default {0}
#define firefly_ux_v1_DisplayConfiguration_init_default {0}
#define firefly_ux_v1_SetDisplayConfigurationRequest_init_default {0, false, firefly_ux_v1_DisplayConfiguration_init_default}
#define firefly_ux_v1_SetDisplayConfigurationResponse_init_default {0}
#define firefly_ux_v1_GetDisplayConfigurationRequest_init_default {0}
#define firefly_ux_v1_GetDisplayConfigurationResponse_init_default {false, firefly_ux_v1_DisplayConfiguration_init_default}
#define firefly_ux_v1_NavigateOperation_init_default {0}
#define firefly_ux_v1_FunctionOperation_init_default {0}
#define firefly_ux_v1_ButtonCondition_init_default {0, 0}
#define firefly_ux_v1_TouchCondition_init_default {0, false, firefly_ux_v1_Area_init_default}
#define firefly_ux_v1_EventInteractionConfiguration_init_default {0, {firefly_ux_v1_ButtonCondition_init_default}, 0, {firefly_ux_v1_NavigateOperation_init_default}}
#define firefly_ux_v1_ScreenInteractionConfiguration_init_default {0, 0, {firefly_ux_v1_EventInteractionConfiguration_init_default, firefly_ux_v1_EventInteractionConfiguration_init_default, firefly_ux_v1_EventInteractionConfiguration_init_default, firefly_ux_v1_EventInteractionConfiguration_init_default}}
#define firefly_ux_v1_InteractionConfiguration_init_default {0, {firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default, firefly_ux_v1_ScreenInteractionConfiguration_init_default}}
#define firefly_ux_v1_GetInteractionConfigurationRequest_init_default {0}
#define firefly_ux_v1_GetInteractionConfigurationResponse_init_default {false, firefly_ux_v1_InteractionConfiguration_init_default}
#define firefly_ux_v1_SetInteractionConfigurationRequest_init_default {0, false, firefly_ux_v1_InteractionConfiguration_init_default}
#define firefly_ux_v1_SetInteractionConfigurationResponse_init_default {0}
#define firefly_ux_v1_Completed_init_zero        {0}
#define firefly_ux_v1_Point_init_zero            {0, 0}
#define firefly_ux_v1_Area_init_zero             {0, 0, 0, 0}
#define firefly_ux_v1_ColorFrameBuffer_init_zero {0, 0, 0}
#define firefly_ux_v1_GrayFrameBuffer_init_zero  {0}
#define firefly_ux_v1_GetDisplayMetadataRequest_init_zero {0}
#define firefly_ux_v1_GetDisplayMetadataResponse_init_zero {0, 0, 0, {firefly_ux_v1_ColorFrameBuffer_init_zero}}
#define firefly_ux_v1_FrameBufferReadRequest_init_zero {0, false, firefly_ux_v1_Area_init_zero}
#define firefly_ux_v1_FrameBufferRead_init_zero  {{0, {0}}}
#define firefly_ux_v1_FrameBufferReadResponse_init_zero {0, {firefly_ux_v1_FrameBufferRead_init_zero}}
#define firefly_ux_v1_GetScreenRequest_init_zero {0}
#define firefly_ux_v1_GetScreenResponse_init_zero {0}
#define firefly_ux_v1_SetScreenRequest_init_zero {0, 0}
#define firefly_ux_v1_SetScreenResponse_init_zero {0}
#define firefly_ux_v1_ButtonEvent_init_zero      {0, 0, 0}
#define firefly_ux_v1_TouchEvent_init_zero       {0, 0, 0, 0}
#define firefly_ux_v1_InputEvent_init_zero       {0, 0, {firefly_ux_v1_ButtonEvent_init_zero}}
#define firefly_ux_v1_SendInputEventsRequest_init_zero {0, 0, {firefly_ux_v1_InputEvent_init_zero, firefly_ux_v1_InputEvent_init_zero, firefly_ux_v1_InputEvent_init_zero, firefly_ux_v1_InputEvent_init_zero, firefly_ux_v1_InputEvent_init_zero, firefly_ux_v1_InputEvent_init_zero, firefly_ux_v1_InputEvent_init_zero, firefly_ux_v1_InputEvent_init_zero}}
#define firefly_ux_v1_SendInputEventsResponse_init_zero {0}
#define firefly_ux_v1_UpdateRequest_init_zero    {0}
#define firefly_ux_v1_UpdateResponse_init_zero   {0}
#define firefly_ux_v1_SetUpdateEnabledRequest_init_zero {0, 0}
#define firefly_ux_v1_SetUpdateEnabledResponse_init_zero {0}
#define firefly_ux_v1_GetUpdateEnabledRequest_init_zero {0}
#define firefly_ux_v1_GetUpdateEnabledResponse_init_zero {0}
#define firefly_ux_v1_DisplayConfiguration_init_zero {0}
#define firefly_ux_v1_SetDisplayConfigurationRequest_init_zero {0, false, firefly_ux_v1_DisplayConfiguration_init_zero}
#define firefly_ux_v1_SetDisplayConfigurationResponse_init_zero {0}
#define firefly_ux_v1_GetDisplayConfigurationRequest_init_zero {0}
#define firefly_ux_v1_GetDisplayConfigurationResponse_init_zero {false, firefly_ux_v1_DisplayConfiguration_init_zero}
#define firefly_ux_v1_NavigateOperation_init_zero {0}
#define firefly_ux_v1_FunctionOperation_init_zero {0}
#define firefly_ux_v1_ButtonCondition_init_zero  {0, 0}
#define firefly_ux_v1_TouchCondition_init_zero   {0, false, firefly_ux_v1_Area_init_zero}
#define firefly_ux_v1_EventInteractionConfiguration_init_zero {0, {firefly_ux_v1_ButtonCondition_init_zero}, 0, {firefly_ux_v1_NavigateOperation_init_zero}}
#define firefly_ux_v1_ScreenInteractionConfiguration_init_zero {0, 0, {firefly_ux_v1_EventInteractionConfiguration_init_zero, firefly_ux_v1_EventInteractionConfiguration_init_zero, firefly_ux_v1_EventInteractionConfiguration_init_zero, firefly_ux_v1_EventInteractionConfiguration_init_zero}}
#define firefly_ux_v1_InteractionConfiguration_init_zero {0, {firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero, firefly_ux_v1_ScreenInteractionConfiguration_init_zero}}
#define firefly_ux_v1_GetInteractionConfigurationRequest_init_zero {0}
#define firefly_ux_v1_GetInteractionConfigurationResponse_init_zero {false, firefly_ux_v1_InteractionConfiguration_init_zero}
#define firefly_ux_v1_SetInteractionConfigurationRequest_init_zero {0, false, firefly_ux_v1_InteractionConfiguration_init_zero}
#define firefly_ux_v1_SetInteractionConfigurationResponse_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define firefly_ux_v1_Area_x_tag                 1
#define firefly_ux_v1_Area_y_tag                 2
#define firefly_ux_v1_Area_width_tag             3
#define firefly_ux_v1_Area_height_tag            4
#define firefly_ux_v1_ButtonCondition_gesture_tag 1
#define firefly_ux_v1_ButtonCondition_button_tag 2
#define firefly_ux_v1_ButtonEvent_gesture_tag    1
#define firefly_ux_v1_ButtonEvent_action_tag     2
#define firefly_ux_v1_ButtonEvent_button_tag     3
#define firefly_ux_v1_ColorFrameBuffer_r_tag     1
#define firefly_ux_v1_ColorFrameBuffer_g_tag     2
#define firefly_ux_v1_ColorFrameBuffer_b_tag     3
#define firefly_ux_v1_DisplayConfiguration_timeout_tag 1
#define firefly_ux_v1_FrameBufferRead_data_tag   1
#define firefly_ux_v1_FunctionOperation_function_identifier_tag 1
#define firefly_ux_v1_GetDisplayConfigurationRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_GetDisplayMetadataRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_GetInteractionConfigurationRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_GetScreenRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_GetScreenResponse_screen_identifier_tag 1
#define firefly_ux_v1_GetUpdateEnabledRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_GetUpdateEnabledResponse_enabled_tag 1
#define firefly_ux_v1_GrayFrameBuffer_depth_tag  1
#define firefly_ux_v1_NavigateOperation_screen_identifier_tag 1
#define firefly_ux_v1_Point_x_tag                1
#define firefly_ux_v1_Point_y_tag                2
#define firefly_ux_v1_SetScreenRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_SetScreenRequest_screen_identifier_tag 2
#define firefly_ux_v1_SetUpdateEnabledRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_SetUpdateEnabledRequest_enabled_tag 2
#define firefly_ux_v1_TouchEvent_gesture_tag     1
#define firefly_ux_v1_TouchEvent_action_tag      2
#define firefly_ux_v1_TouchEvent_x_tag           3
#define firefly_ux_v1_TouchEvent_y_tag           4
#define firefly_ux_v1_UpdateRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_FrameBufferReadRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_FrameBufferReadRequest_area_tag 2
#define firefly_ux_v1_FrameBufferReadResponse_read_tag 1
#define firefly_ux_v1_FrameBufferReadResponse_completed_tag 2
#define firefly_ux_v1_GetDisplayConfigurationResponse_configuration_tag 1
#define firefly_ux_v1_GetDisplayMetadataResponse_width_tag 1
#define firefly_ux_v1_GetDisplayMetadataResponse_height_tag 2
#define firefly_ux_v1_GetDisplayMetadataResponse_color_tag 3
#define firefly_ux_v1_GetDisplayMetadataResponse_gray_tag 4
#define firefly_ux_v1_InputEvent_delay_tag       1
#define firefly_ux_v1_InputEvent_button_event_tag 2
#define firefly_ux_v1_InputEvent_touch_event_tag 3
#define firefly_ux_v1_SetDisplayConfigurationRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_SetDisplayConfigurationRequest_configuration_tag 2
#define firefly_ux_v1_TouchCondition_gesture_tag 1
#define firefly_ux_v1_TouchCondition_area_tag    2
#define firefly_ux_v1_EventInteractionConfiguration_button_condition_tag 1
#define firefly_ux_v1_EventInteractionConfiguration_touch_condition_tag 2
#define firefly_ux_v1_EventInteractionConfiguration_navigate_operation_tag 3
#define firefly_ux_v1_EventInteractionConfiguration_function_operation_tag 4
#define firefly_ux_v1_SendInputEventsRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_SendInputEventsRequest_input_events_tag 2
#define firefly_ux_v1_ScreenInteractionConfiguration_screen_identifier_tag 1
#define firefly_ux_v1_ScreenInteractionConfiguration_event_interaction_configurations_tag 2
#define firefly_ux_v1_InteractionConfiguration_screen_interaction_configurations_tag 1
#define firefly_ux_v1_GetInteractionConfigurationResponse_configuration_tag 1
#define firefly_ux_v1_SetInteractionConfigurationRequest_user_interface_identifier_tag 1
#define firefly_ux_v1_SetInteractionConfigurationRequest_configuration_tag 2

/* Struct field encoding specification for nanopb */
#define firefly_ux_v1_Completed_FIELDLIST(X, a) \

#define firefly_ux_v1_Completed_CALLBACK NULL
#define firefly_ux_v1_Completed_DEFAULT NULL

#define firefly_ux_v1_Point_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, SINT32,   y,                 2)
#define firefly_ux_v1_Point_CALLBACK NULL
#define firefly_ux_v1_Point_DEFAULT NULL

#define firefly_ux_v1_Area_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   x,                 1) \
X(a, STATIC,   SINGULAR, SINT32,   y,                 2) \
X(a, STATIC,   SINGULAR, SINT32,   width,             3) \
X(a, STATIC,   SINGULAR, SINT32,   height,            4)
#define firefly_ux_v1_Area_CALLBACK NULL
#define firefly_ux_v1_Area_DEFAULT NULL

#define firefly_ux_v1_ColorFrameBuffer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   r,                 1) \
X(a, STATIC,   SINGULAR, UINT32,   g,                 2) \
X(a, STATIC,   SINGULAR, UINT32,   b,                 3)
#define firefly_ux_v1_ColorFrameBuffer_CALLBACK NULL
#define firefly_ux_v1_ColorFrameBuffer_DEFAULT NULL

#define firefly_ux_v1_GrayFrameBuffer_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   depth,             1)
#define firefly_ux_v1_GrayFrameBuffer_CALLBACK NULL
#define firefly_ux_v1_GrayFrameBuffer_DEFAULT NULL

#define firefly_ux_v1_GetDisplayMetadataRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1)
#define firefly_ux_v1_GetDisplayMetadataRequest_CALLBACK NULL
#define firefly_ux_v1_GetDisplayMetadataRequest_DEFAULT NULL

#define firefly_ux_v1_GetDisplayMetadataResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   width,             1) \
X(a, STATIC,   SINGULAR, UINT32,   height,            2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (frame_buffer,color,frame_buffer.color),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (frame_buffer,gray,frame_buffer.gray),   4)
#define firefly_ux_v1_GetDisplayMetadataResponse_CALLBACK NULL
#define firefly_ux_v1_GetDisplayMetadataResponse_DEFAULT NULL
#define firefly_ux_v1_GetDisplayMetadataResponse_frame_buffer_color_MSGTYPE firefly_ux_v1_ColorFrameBuffer
#define firefly_ux_v1_GetDisplayMetadataResponse_frame_buffer_gray_MSGTYPE firefly_ux_v1_GrayFrameBuffer

#define firefly_ux_v1_FrameBufferReadRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  area,              2)
#define firefly_ux_v1_FrameBufferReadRequest_CALLBACK NULL
#define firefly_ux_v1_FrameBufferReadRequest_DEFAULT NULL
#define firefly_ux_v1_FrameBufferReadRequest_area_MSGTYPE firefly_ux_v1_Area

#define firefly_ux_v1_FrameBufferRead_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    data,              1)
#define firefly_ux_v1_FrameBufferRead_CALLBACK NULL
#define firefly_ux_v1_FrameBufferRead_DEFAULT NULL

#define firefly_ux_v1_FrameBufferReadResponse_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,read,message.read),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,completed,message.completed),   2)
#define firefly_ux_v1_FrameBufferReadResponse_CALLBACK NULL
#define firefly_ux_v1_FrameBufferReadResponse_DEFAULT NULL
#define firefly_ux_v1_FrameBufferReadResponse_message_read_MSGTYPE firefly_ux_v1_FrameBufferRead
#define firefly_ux_v1_FrameBufferReadResponse_message_completed_MSGTYPE firefly_ux_v1_Completed

#define firefly_ux_v1_GetScreenRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1)
#define firefly_ux_v1_GetScreenRequest_CALLBACK NULL
#define firefly_ux_v1_GetScreenRequest_DEFAULT NULL

#define firefly_ux_v1_GetScreenResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   screen_identifier,   1)
#define firefly_ux_v1_GetScreenResponse_CALLBACK NULL
#define firefly_ux_v1_GetScreenResponse_DEFAULT NULL

#define firefly_ux_v1_SetScreenRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1) \
X(a, STATIC,   SINGULAR, UINT32,   screen_identifier,   2)
#define firefly_ux_v1_SetScreenRequest_CALLBACK NULL
#define firefly_ux_v1_SetScreenRequest_DEFAULT NULL

#define firefly_ux_v1_SetScreenResponse_FIELDLIST(X, a) \

#define firefly_ux_v1_SetScreenResponse_CALLBACK NULL
#define firefly_ux_v1_SetScreenResponse_DEFAULT NULL

#define firefly_ux_v1_ButtonEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gesture,           1) \
X(a, STATIC,   SINGULAR, UINT32,   action,            2) \
X(a, STATIC,   SINGULAR, UINT32,   button,            3)
#define firefly_ux_v1_ButtonEvent_CALLBACK NULL
#define firefly_ux_v1_ButtonEvent_DEFAULT NULL

#define firefly_ux_v1_TouchEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gesture,           1) \
X(a, STATIC,   SINGULAR, UINT32,   action,            2) \
X(a, STATIC,   SINGULAR, INT32,    x,                 3) \
X(a, STATIC,   SINGULAR, INT32,    y,                 4)
#define firefly_ux_v1_TouchEvent_CALLBACK NULL
#define firefly_ux_v1_TouchEvent_DEFAULT NULL

#define firefly_ux_v1_InputEvent_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    delay,             1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,button_event,event.button_event),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (event,touch_event,event.touch_event),   3)
#define firefly_ux_v1_InputEvent_CALLBACK NULL
#define firefly_ux_v1_InputEvent_DEFAULT NULL
#define firefly_ux_v1_InputEvent_event_button_event_MSGTYPE firefly_ux_v1_ButtonEvent
#define firefly_ux_v1_InputEvent_event_touch_event_MSGTYPE firefly_ux_v1_TouchEvent

#define firefly_ux_v1_SendInputEventsRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1) \
X(a, STATIC,   REPEATED, MESSAGE,  input_events,      2)
#define firefly_ux_v1_SendInputEventsRequest_CALLBACK NULL
#define firefly_ux_v1_SendInputEventsRequest_DEFAULT NULL
#define firefly_ux_v1_SendInputEventsRequest_input_events_MSGTYPE firefly_ux_v1_InputEvent

#define firefly_ux_v1_SendInputEventsResponse_FIELDLIST(X, a) \

#define firefly_ux_v1_SendInputEventsResponse_CALLBACK NULL
#define firefly_ux_v1_SendInputEventsResponse_DEFAULT NULL

#define firefly_ux_v1_UpdateRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1)
#define firefly_ux_v1_UpdateRequest_CALLBACK NULL
#define firefly_ux_v1_UpdateRequest_DEFAULT NULL

#define firefly_ux_v1_UpdateResponse_FIELDLIST(X, a) \

#define firefly_ux_v1_UpdateResponse_CALLBACK NULL
#define firefly_ux_v1_UpdateResponse_DEFAULT NULL

#define firefly_ux_v1_SetUpdateEnabledRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           2)
#define firefly_ux_v1_SetUpdateEnabledRequest_CALLBACK NULL
#define firefly_ux_v1_SetUpdateEnabledRequest_DEFAULT NULL

#define firefly_ux_v1_SetUpdateEnabledResponse_FIELDLIST(X, a) \

#define firefly_ux_v1_SetUpdateEnabledResponse_CALLBACK NULL
#define firefly_ux_v1_SetUpdateEnabledResponse_DEFAULT NULL

#define firefly_ux_v1_GetUpdateEnabledRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1)
#define firefly_ux_v1_GetUpdateEnabledRequest_CALLBACK NULL
#define firefly_ux_v1_GetUpdateEnabledRequest_DEFAULT NULL

#define firefly_ux_v1_GetUpdateEnabledResponse_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     enabled,           1)
#define firefly_ux_v1_GetUpdateEnabledResponse_CALLBACK NULL
#define firefly_ux_v1_GetUpdateEnabledResponse_DEFAULT NULL

#define firefly_ux_v1_DisplayConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timeout,           1)
#define firefly_ux_v1_DisplayConfiguration_CALLBACK NULL
#define firefly_ux_v1_DisplayConfiguration_DEFAULT NULL

#define firefly_ux_v1_SetDisplayConfigurationRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  configuration,     2)
#define firefly_ux_v1_SetDisplayConfigurationRequest_CALLBACK NULL
#define firefly_ux_v1_SetDisplayConfigurationRequest_DEFAULT NULL
#define firefly_ux_v1_SetDisplayConfigurationRequest_configuration_MSGTYPE firefly_ux_v1_DisplayConfiguration

#define firefly_ux_v1_SetDisplayConfigurationResponse_FIELDLIST(X, a) \

#define firefly_ux_v1_SetDisplayConfigurationResponse_CALLBACK NULL
#define firefly_ux_v1_SetDisplayConfigurationResponse_DEFAULT NULL

#define firefly_ux_v1_GetDisplayConfigurationRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1)
#define firefly_ux_v1_GetDisplayConfigurationRequest_CALLBACK NULL
#define firefly_ux_v1_GetDisplayConfigurationRequest_DEFAULT NULL

#define firefly_ux_v1_GetDisplayConfigurationResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  configuration,     1)
#define firefly_ux_v1_GetDisplayConfigurationResponse_CALLBACK NULL
#define firefly_ux_v1_GetDisplayConfigurationResponse_DEFAULT NULL
#define firefly_ux_v1_GetDisplayConfigurationResponse_configuration_MSGTYPE firefly_ux_v1_DisplayConfiguration

#define firefly_ux_v1_NavigateOperation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   screen_identifier,   1)
#define firefly_ux_v1_NavigateOperation_CALLBACK NULL
#define firefly_ux_v1_NavigateOperation_DEFAULT NULL

#define firefly_ux_v1_FunctionOperation_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   function_identifier,   1)
#define firefly_ux_v1_FunctionOperation_CALLBACK NULL
#define firefly_ux_v1_FunctionOperation_DEFAULT NULL

#define firefly_ux_v1_ButtonCondition_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gesture,           1) \
X(a, STATIC,   SINGULAR, UINT32,   button,            2)
#define firefly_ux_v1_ButtonCondition_CALLBACK NULL
#define firefly_ux_v1_ButtonCondition_DEFAULT NULL

#define firefly_ux_v1_TouchCondition_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   gesture,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  area,              2)
#define firefly_ux_v1_TouchCondition_CALLBACK NULL
#define firefly_ux_v1_TouchCondition_DEFAULT NULL
#define firefly_ux_v1_TouchCondition_area_MSGTYPE firefly_ux_v1_Area

#define firefly_ux_v1_EventInteractionConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (condition,button_condition,condition.button_condition),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (condition,touch_condition,condition.touch_condition),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (operation,navigate_operation,operation.navigate_operation),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (operation,function_operation,operation.function_operation),   4)
#define firefly_ux_v1_EventInteractionConfiguration_CALLBACK NULL
#define firefly_ux_v1_EventInteractionConfiguration_DEFAULT NULL
#define firefly_ux_v1_EventInteractionConfiguration_condition_button_condition_MSGTYPE firefly_ux_v1_ButtonCondition
#define firefly_ux_v1_EventInteractionConfiguration_condition_touch_condition_MSGTYPE firefly_ux_v1_TouchCondition
#define firefly_ux_v1_EventInteractionConfiguration_operation_navigate_operation_MSGTYPE firefly_ux_v1_NavigateOperation
#define firefly_ux_v1_EventInteractionConfiguration_operation_function_operation_MSGTYPE firefly_ux_v1_FunctionOperation

#define firefly_ux_v1_ScreenInteractionConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   screen_identifier,   1) \
X(a, STATIC,   REPEATED, MESSAGE,  event_interaction_configurations,   2)
#define firefly_ux_v1_ScreenInteractionConfiguration_CALLBACK NULL
#define firefly_ux_v1_ScreenInteractionConfiguration_DEFAULT NULL
#define firefly_ux_v1_ScreenInteractionConfiguration_event_interaction_configurations_MSGTYPE firefly_ux_v1_EventInteractionConfiguration

#define firefly_ux_v1_InteractionConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, MESSAGE,  screen_interaction_configurations,   1)
#define firefly_ux_v1_InteractionConfiguration_CALLBACK NULL
#define firefly_ux_v1_InteractionConfiguration_DEFAULT NULL
#define firefly_ux_v1_InteractionConfiguration_screen_interaction_configurations_MSGTYPE firefly_ux_v1_ScreenInteractionConfiguration

#define firefly_ux_v1_GetInteractionConfigurationRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1)
#define firefly_ux_v1_GetInteractionConfigurationRequest_CALLBACK NULL
#define firefly_ux_v1_GetInteractionConfigurationRequest_DEFAULT NULL

#define firefly_ux_v1_GetInteractionConfigurationResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  configuration,     1)
#define firefly_ux_v1_GetInteractionConfigurationResponse_CALLBACK NULL
#define firefly_ux_v1_GetInteractionConfigurationResponse_DEFAULT NULL
#define firefly_ux_v1_GetInteractionConfigurationResponse_configuration_MSGTYPE firefly_ux_v1_InteractionConfiguration

#define firefly_ux_v1_SetInteractionConfigurationRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   user_interface_identifier,   1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  configuration,     2)
#define firefly_ux_v1_SetInteractionConfigurationRequest_CALLBACK NULL
#define firefly_ux_v1_SetInteractionConfigurationRequest_DEFAULT NULL
#define firefly_ux_v1_SetInteractionConfigurationRequest_configuration_MSGTYPE firefly_ux_v1_InteractionConfiguration

#define firefly_ux_v1_SetInteractionConfigurationResponse_FIELDLIST(X, a) \

#define firefly_ux_v1_SetInteractionConfigurationResponse_CALLBACK NULL
#define firefly_ux_v1_SetInteractionConfigurationResponse_DEFAULT NULL

extern const pb_msgdesc_t firefly_ux_v1_Completed_msg;
extern const pb_msgdesc_t firefly_ux_v1_Point_msg;
extern const pb_msgdesc_t firefly_ux_v1_Area_msg;
extern const pb_msgdesc_t firefly_ux_v1_ColorFrameBuffer_msg;
extern const pb_msgdesc_t firefly_ux_v1_GrayFrameBuffer_msg;
extern const pb_msgdesc_t firefly_ux_v1_GetDisplayMetadataRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_GetDisplayMetadataResponse_msg;
extern const pb_msgdesc_t firefly_ux_v1_FrameBufferReadRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_FrameBufferRead_msg;
extern const pb_msgdesc_t firefly_ux_v1_FrameBufferReadResponse_msg;
extern const pb_msgdesc_t firefly_ux_v1_GetScreenRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_GetScreenResponse_msg;
extern const pb_msgdesc_t firefly_ux_v1_SetScreenRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_SetScreenResponse_msg;
extern const pb_msgdesc_t firefly_ux_v1_ButtonEvent_msg;
extern const pb_msgdesc_t firefly_ux_v1_TouchEvent_msg;
extern const pb_msgdesc_t firefly_ux_v1_InputEvent_msg;
extern const pb_msgdesc_t firefly_ux_v1_SendInputEventsRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_SendInputEventsResponse_msg;
extern const pb_msgdesc_t firefly_ux_v1_UpdateRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_UpdateResponse_msg;
extern const pb_msgdesc_t firefly_ux_v1_SetUpdateEnabledRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_SetUpdateEnabledResponse_msg;
extern const pb_msgdesc_t firefly_ux_v1_GetUpdateEnabledRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_GetUpdateEnabledResponse_msg;
extern const pb_msgdesc_t firefly_ux_v1_DisplayConfiguration_msg;
extern const pb_msgdesc_t firefly_ux_v1_SetDisplayConfigurationRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_SetDisplayConfigurationResponse_msg;
extern const pb_msgdesc_t firefly_ux_v1_GetDisplayConfigurationRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_GetDisplayConfigurationResponse_msg;
extern const pb_msgdesc_t firefly_ux_v1_NavigateOperation_msg;
extern const pb_msgdesc_t firefly_ux_v1_FunctionOperation_msg;
extern const pb_msgdesc_t firefly_ux_v1_ButtonCondition_msg;
extern const pb_msgdesc_t firefly_ux_v1_TouchCondition_msg;
extern const pb_msgdesc_t firefly_ux_v1_EventInteractionConfiguration_msg;
extern const pb_msgdesc_t firefly_ux_v1_ScreenInteractionConfiguration_msg;
extern const pb_msgdesc_t firefly_ux_v1_InteractionConfiguration_msg;
extern const pb_msgdesc_t firefly_ux_v1_GetInteractionConfigurationRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_GetInteractionConfigurationResponse_msg;
extern const pb_msgdesc_t firefly_ux_v1_SetInteractionConfigurationRequest_msg;
extern const pb_msgdesc_t firefly_ux_v1_SetInteractionConfigurationResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define firefly_ux_v1_Completed_fields &firefly_ux_v1_Completed_msg
#define firefly_ux_v1_Point_fields &firefly_ux_v1_Point_msg
#define firefly_ux_v1_Area_fields &firefly_ux_v1_Area_msg
#define firefly_ux_v1_ColorFrameBuffer_fields &firefly_ux_v1_ColorFrameBuffer_msg
#define firefly_ux_v1_GrayFrameBuffer_fields &firefly_ux_v1_GrayFrameBuffer_msg
#define firefly_ux_v1_GetDisplayMetadataRequest_fields &firefly_ux_v1_GetDisplayMetadataRequest_msg
#define firefly_ux_v1_GetDisplayMetadataResponse_fields &firefly_ux_v1_GetDisplayMetadataResponse_msg
#define firefly_ux_v1_FrameBufferReadRequest_fields &firefly_ux_v1_FrameBufferReadRequest_msg
#define firefly_ux_v1_FrameBufferRead_fields &firefly_ux_v1_FrameBufferRead_msg
#define firefly_ux_v1_FrameBufferReadResponse_fields &firefly_ux_v1_FrameBufferReadResponse_msg
#define firefly_ux_v1_GetScreenRequest_fields &firefly_ux_v1_GetScreenRequest_msg
#define firefly_ux_v1_GetScreenResponse_fields &firefly_ux_v1_GetScreenResponse_msg
#define firefly_ux_v1_SetScreenRequest_fields &firefly_ux_v1_SetScreenRequest_msg
#define firefly_ux_v1_SetScreenResponse_fields &firefly_ux_v1_SetScreenResponse_msg
#define firefly_ux_v1_ButtonEvent_fields &firefly_ux_v1_ButtonEvent_msg
#define firefly_ux_v1_TouchEvent_fields &firefly_ux_v1_TouchEvent_msg
#define firefly_ux_v1_InputEvent_fields &firefly_ux_v1_InputEvent_msg
#define firefly_ux_v1_SendInputEventsRequest_fields &firefly_ux_v1_SendInputEventsRequest_msg
#define firefly_ux_v1_SendInputEventsResponse_fields &firefly_ux_v1_SendInputEventsResponse_msg
#define firefly_ux_v1_UpdateRequest_fields &firefly_ux_v1_UpdateRequest_msg
#define firefly_ux_v1_UpdateResponse_fields &firefly_ux_v1_UpdateResponse_msg
#define firefly_ux_v1_SetUpdateEnabledRequest_fields &firefly_ux_v1_SetUpdateEnabledRequest_msg
#define firefly_ux_v1_SetUpdateEnabledResponse_fields &firefly_ux_v1_SetUpdateEnabledResponse_msg
#define firefly_ux_v1_GetUpdateEnabledRequest_fields &firefly_ux_v1_GetUpdateEnabledRequest_msg
#define firefly_ux_v1_GetUpdateEnabledResponse_fields &firefly_ux_v1_GetUpdateEnabledResponse_msg
#define firefly_ux_v1_DisplayConfiguration_fields &firefly_ux_v1_DisplayConfiguration_msg
#define firefly_ux_v1_SetDisplayConfigurationRequest_fields &firefly_ux_v1_SetDisplayConfigurationRequest_msg
#define firefly_ux_v1_SetDisplayConfigurationResponse_fields &firefly_ux_v1_SetDisplayConfigurationResponse_msg
#define firefly_ux_v1_GetDisplayConfigurationRequest_fields &firefly_ux_v1_GetDisplayConfigurationRequest_msg
#define firefly_ux_v1_GetDisplayConfigurationResponse_fields &firefly_ux_v1_GetDisplayConfigurationResponse_msg
#define firefly_ux_v1_NavigateOperation_fields &firefly_ux_v1_NavigateOperation_msg
#define firefly_ux_v1_FunctionOperation_fields &firefly_ux_v1_FunctionOperation_msg
#define firefly_ux_v1_ButtonCondition_fields &firefly_ux_v1_ButtonCondition_msg
#define firefly_ux_v1_TouchCondition_fields &firefly_ux_v1_TouchCondition_msg
#define firefly_ux_v1_EventInteractionConfiguration_fields &firefly_ux_v1_EventInteractionConfiguration_msg
#define firefly_ux_v1_ScreenInteractionConfiguration_fields &firefly_ux_v1_ScreenInteractionConfiguration_msg
#define firefly_ux_v1_InteractionConfiguration_fields &firefly_ux_v1_InteractionConfiguration_msg
#define firefly_ux_v1_GetInteractionConfigurationRequest_fields &firefly_ux_v1_GetInteractionConfigurationRequest_msg
#define firefly_ux_v1_GetInteractionConfigurationResponse_fields &firefly_ux_v1_GetInteractionConfigurationResponse_msg
#define firefly_ux_v1_SetInteractionConfigurationRequest_fields &firefly_ux_v1_SetInteractionConfigurationRequest_msg
#define firefly_ux_v1_SetInteractionConfigurationResponse_fields &firefly_ux_v1_SetInteractionConfigurationResponse_msg

/* Maximum encoded size of messages (where known) */
#define firefly_ux_v1_Area_size                  24
#define firefly_ux_v1_ButtonCondition_size       12
#define firefly_ux_v1_ButtonEvent_size           18
#define firefly_ux_v1_ColorFrameBuffer_size      18
#define firefly_ux_v1_Completed_size             0
#define firefly_ux_v1_DisplayConfiguration_size  6
#define firefly_ux_v1_EventInteractionConfiguration_size 42
#define firefly_ux_v1_FrameBufferReadRequest_size 32
#define firefly_ux_v1_FrameBufferReadResponse_size 262
#define firefly_ux_v1_FrameBufferRead_size       259
#define firefly_ux_v1_FunctionOperation_size     6
#define firefly_ux_v1_GetDisplayConfigurationRequest_size 6
#define firefly_ux_v1_GetDisplayConfigurationResponse_size 8
#define firefly_ux_v1_GetDisplayMetadataRequest_size 6
#define firefly_ux_v1_GetDisplayMetadataResponse_size 32
#define firefly_ux_v1_GetInteractionConfigurationRequest_size 6
#define firefly_ux_v1_GetInteractionConfigurationResponse_size 5923
#define firefly_ux_v1_GetScreenRequest_size      6
#define firefly_ux_v1_GetScreenResponse_size     6
#define firefly_ux_v1_GetUpdateEnabledRequest_size 6
#define firefly_ux_v1_GetUpdateEnabledResponse_size 2
#define firefly_ux_v1_GrayFrameBuffer_size       6
#define firefly_ux_v1_InputEvent_size            41
#define firefly_ux_v1_InteractionConfiguration_size 5920
#define firefly_ux_v1_NavigateOperation_size     6
#define firefly_ux_v1_Point_size                 12
#define firefly_ux_v1_ScreenInteractionConfiguration_size 182
#define firefly_ux_v1_SendInputEventsRequest_size 350
#define firefly_ux_v1_SendInputEventsResponse_size 0
#define firefly_ux_v1_SetDisplayConfigurationRequest_size 14
#define firefly_ux_v1_SetDisplayConfigurationResponse_size 0
#define firefly_ux_v1_SetInteractionConfigurationRequest_size 5929
#define firefly_ux_v1_SetInteractionConfigurationResponse_size 0
#define firefly_ux_v1_SetScreenRequest_size      12
#define firefly_ux_v1_SetScreenResponse_size     0
#define firefly_ux_v1_SetUpdateEnabledRequest_size 8
#define firefly_ux_v1_SetUpdateEnabledResponse_size 0
#define firefly_ux_v1_TouchCondition_size        32
#define firefly_ux_v1_TouchEvent_size            34
#define firefly_ux_v1_UpdateRequest_size         6
#define firefly_ux_v1_UpdateResponse_size        0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
