/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.6 */

#include "ux.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(firefly_ux_v1_Completed, firefly_ux_v1_Completed, AUTO)


PB_BIND(firefly_ux_v1_Point, firefly_ux_v1_Point, AUTO)


PB_BIND(firefly_ux_v1_Area, firefly_ux_v1_Area, AUTO)


PB_BIND(firefly_ux_v1_ColorFrameBuffer, firefly_ux_v1_ColorFrameBuffer, AUTO)


PB_BIND(firefly_ux_v1_GrayFrameBuffer, firefly_ux_v1_GrayFrameBuffer, AUTO)


PB_BIND(firefly_ux_v1_GetDisplayMetadataRequest, firefly_ux_v1_GetDisplayMetadataRequest, AUTO)


PB_BIND(firefly_ux_v1_GetDisplayMetadataResponse, firefly_ux_v1_GetDisplayMetadataResponse, AUTO)


PB_BIND(firefly_ux_v1_FrameBufferReadRequest, firefly_ux_v1_FrameBufferReadRequest, AUTO)


PB_BIND(firefly_ux_v1_FrameBufferRead, firefly_ux_v1_FrameBufferRead, 2)


PB_BIND(firefly_ux_v1_FrameBufferReadResponse, firefly_ux_v1_FrameBufferReadResponse, 2)


PB_BIND(firefly_ux_v1_GetScreenRequest, firefly_ux_v1_GetScreenRequest, AUTO)


PB_BIND(firefly_ux_v1_GetScreenResponse, firefly_ux_v1_GetScreenResponse, AUTO)


PB_BIND(firefly_ux_v1_SetScreenRequest, firefly_ux_v1_SetScreenRequest, AUTO)


PB_BIND(firefly_ux_v1_SetScreenResponse, firefly_ux_v1_SetScreenResponse, AUTO)


PB_BIND(firefly_ux_v1_ButtonEvent, firefly_ux_v1_ButtonEvent, AUTO)


PB_BIND(firefly_ux_v1_TouchEvent, firefly_ux_v1_TouchEvent, AUTO)


PB_BIND(firefly_ux_v1_InputEvent, firefly_ux_v1_InputEvent, AUTO)


PB_BIND(firefly_ux_v1_SendInputEventsRequest, firefly_ux_v1_SendInputEventsRequest, AUTO)


PB_BIND(firefly_ux_v1_SendInputEventsResponse, firefly_ux_v1_SendInputEventsResponse, AUTO)


PB_BIND(firefly_ux_v1_UpdateRequest, firefly_ux_v1_UpdateRequest, AUTO)


PB_BIND(firefly_ux_v1_UpdateResponse, firefly_ux_v1_UpdateResponse, AUTO)


PB_BIND(firefly_ux_v1_SetUpdateEnabledRequest, firefly_ux_v1_SetUpdateEnabledRequest, AUTO)


PB_BIND(firefly_ux_v1_SetUpdateEnabledResponse, firefly_ux_v1_SetUpdateEnabledResponse, AUTO)


PB_BIND(firefly_ux_v1_GetUpdateEnabledRequest, firefly_ux_v1_GetUpdateEnabledRequest, AUTO)


PB_BIND(firefly_ux_v1_GetUpdateEnabledResponse, firefly_ux_v1_GetUpdateEnabledResponse, AUTO)


PB_BIND(firefly_ux_v1_DisplayConfiguration, firefly_ux_v1_DisplayConfiguration, AUTO)


PB_BIND(firefly_ux_v1_SetDisplayConfigurationRequest, firefly_ux_v1_SetDisplayConfigurationRequest, AUTO)


PB_BIND(firefly_ux_v1_SetDisplayConfigurationResponse, firefly_ux_v1_SetDisplayConfigurationResponse, AUTO)


PB_BIND(firefly_ux_v1_GetDisplayConfigurationRequest, firefly_ux_v1_GetDisplayConfigurationRequest, AUTO)


PB_BIND(firefly_ux_v1_GetDisplayConfigurationResponse, firefly_ux_v1_GetDisplayConfigurationResponse, AUTO)


PB_BIND(firefly_ux_v1_NavigateOperation, firefly_ux_v1_NavigateOperation, AUTO)


PB_BIND(firefly_ux_v1_FunctionOperation, firefly_ux_v1_FunctionOperation, AUTO)


PB_BIND(firefly_ux_v1_ButtonCondition, firefly_ux_v1_ButtonCondition, AUTO)


PB_BIND(firefly_ux_v1_TouchCondition, firefly_ux_v1_TouchCondition, AUTO)


PB_BIND(firefly_ux_v1_EventInteractionConfiguration, firefly_ux_v1_EventInteractionConfiguration, AUTO)


PB_BIND(firefly_ux_v1_ScreenInteractionConfiguration, firefly_ux_v1_ScreenInteractionConfiguration, AUTO)


PB_BIND(firefly_ux_v1_InteractionConfiguration, firefly_ux_v1_InteractionConfiguration, 4)


PB_BIND(firefly_ux_v1_GetInteractionConfigurationRequest, firefly_ux_v1_GetInteractionConfigurationRequest, AUTO)


PB_BIND(firefly_ux_v1_GetInteractionConfigurationResponse, firefly_ux_v1_GetInteractionConfigurationResponse, 4)


PB_BIND(firefly_ux_v1_SetInteractionConfigurationRequest, firefly_ux_v1_SetInteractionConfigurationRequest, 4)


PB_BIND(firefly_ux_v1_SetInteractionConfigurationResponse, firefly_ux_v1_SetInteractionConfigurationResponse, AUTO)



