# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: options.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\roptions.proto\x12\x12\x66irefly.options.v1\x1a google/protobuf/descriptor.proto:3\n\x08\x63_prefix\x12\x1c.google.protobuf.FileOptions\x18\xe0\xd4\x03 \x01(\t\x88\x01\x01:8\n\rpython_prefix\x12\x1c.google.protobuf.FileOptions\x18\xe1\xd4\x03 \x01(\t\x88\x01\x01:5\n\npackage_id\x12\x1c.google.protobuf.FileOptions\x18\xe2\xd4\x03 \x01(\r\x88\x01\x01:8\n\nservice_id\x12\x1f.google.protobuf.ServiceOptions\x18\xe3\xd4\x03 \x01(\r\x88\x01\x01:6\n\tmethod_id\x12\x1e.google.protobuf.MethodOptions\x18\xe4\xd4\x03 \x01(\r\x88\x01\x01:3\n\x06\x61\x63\x63\x65ss\x12\x1e.google.protobuf.MethodOptions\x18\xe5\xd4\x03 \x01(\r\x88\x01\x01\x62\x06proto3')


C_PREFIX_FIELD_NUMBER = 60000
c_prefix = DESCRIPTOR.extensions_by_name['c_prefix']
PYTHON_PREFIX_FIELD_NUMBER = 60001
python_prefix = DESCRIPTOR.extensions_by_name['python_prefix']
PACKAGE_ID_FIELD_NUMBER = 60002
package_id = DESCRIPTOR.extensions_by_name['package_id']
SERVICE_ID_FIELD_NUMBER = 60003
service_id = DESCRIPTOR.extensions_by_name['service_id']
METHOD_ID_FIELD_NUMBER = 60004
method_id = DESCRIPTOR.extensions_by_name['method_id']
ACCESS_FIELD_NUMBER = 60005
access = DESCRIPTOR.extensions_by_name['access']

if _descriptor._USE_C_DESCRIPTORS == False:
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(c_prefix)
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(python_prefix)
  google_dot_protobuf_dot_descriptor__pb2.FileOptions.RegisterExtension(package_id)
  google_dot_protobuf_dot_descriptor__pb2.ServiceOptions.RegisterExtension(service_id)
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(method_id)
  google_dot_protobuf_dot_descriptor__pb2.MethodOptions.RegisterExtension(access)

  DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
