# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rtc.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import options_pb2 as options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\trtc.proto\x12\x0e\x66irefly.rtc.v1\x1a\roptions.proto\"\x10\n\x0eGetTimeRequest\":\n\x0fGetTimeResponse\x12\x0e\n\x06is_set\x18\x01 \x01(\x08\x12\x0b\n\x03utc\x18\x02 \x01(\x12\x12\n\n\x02us\x18\x03 \x01(\x11\")\n\x0eSetTimeRequest\x12\x0b\n\x03utc\x18\x02 \x01(\x12\x12\n\n\x02us\x18\x03 \x01(\x11\"\x11\n\x0fSetTimeResponse\"`\n\rConfiguration\x12\x18\n\x10time_zone_offset\x18\x01 \x01(\x11\x12\x35\n\x0e\x64isplay_format\x18\x02 \x01(\x0e\x32\x1d.firefly.rtc.v1.DisplayFormat\"\x19\n\x17GetConfigurationRequest\"P\n\x18GetConfigurationResponse\x12\x34\n\rconfiguration\x18\x01 \x01(\x0b\x32\x1d.firefly.rtc.v1.Configuration\"O\n\x17SetConfigurationRequest\x12\x34\n\rconfiguration\x18\x01 \x01(\x0b\x32\x1d.firefly.rtc.v1.Configuration\"\x1a\n\x18SetConfigurationResponse*7\n\rDisplayFormat\x12\x12\n\x0eUse12HourClock\x10\x00\x12\x12\n\x0eUse24HourClock\x10\x01\x32\x89\x03\n\x03RTC\x12P\n\x07getTime\x12\x1e.firefly.rtc.v1.GetTimeRequest\x1a\x1f.firefly.rtc.v1.GetTimeResponse\"\x04\xa0\xa6\x1d\x01\x12P\n\x07setTime\x12\x1e.firefly.rtc.v1.SetTimeRequest\x1a\x1f.firefly.rtc.v1.SetTimeResponse\"\x04\xa0\xa6\x1d\x02\x12k\n\x10getConfiguration\x12\'.firefly.rtc.v1.GetConfigurationRequest\x1a(.firefly.rtc.v1.GetConfigurationResponse\"\x04\xa0\xa6\x1d\x03\x12k\n\x10setConfiguration\x12\'.firefly.rtc.v1.SetConfigurationRequest\x1a(.firefly.rtc.v1.SetConfigurationResponse\"\x04\xa0\xa6\x1d\x04\x1a\x04\x98\xa6\x1d\x01\x42\n\x90\xa6\x1d\n\x82\xa6\x1d\x02\x66\x64\x62\x06proto3')

_DISPLAYFORMAT = DESCRIPTOR.enum_types_by_name['DisplayFormat']
DisplayFormat = enum_type_wrapper.EnumTypeWrapper(_DISPLAYFORMAT)
Use12HourClock = 0
Use24HourClock = 1


_GETTIMEREQUEST = DESCRIPTOR.message_types_by_name['GetTimeRequest']
_GETTIMERESPONSE = DESCRIPTOR.message_types_by_name['GetTimeResponse']
_SETTIMEREQUEST = DESCRIPTOR.message_types_by_name['SetTimeRequest']
_SETTIMERESPONSE = DESCRIPTOR.message_types_by_name['SetTimeResponse']
_CONFIGURATION = DESCRIPTOR.message_types_by_name['Configuration']
_GETCONFIGURATIONREQUEST = DESCRIPTOR.message_types_by_name['GetConfigurationRequest']
_GETCONFIGURATIONRESPONSE = DESCRIPTOR.message_types_by_name['GetConfigurationResponse']
_SETCONFIGURATIONREQUEST = DESCRIPTOR.message_types_by_name['SetConfigurationRequest']
_SETCONFIGURATIONRESPONSE = DESCRIPTOR.message_types_by_name['SetConfigurationResponse']
GetTimeRequest = _reflection.GeneratedProtocolMessageType('GetTimeRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETTIMEREQUEST,
  '__module__' : 'rtc_pb2'
  # @@protoc_insertion_point(class_scope:firefly.rtc.v1.GetTimeRequest)
  })
_sym_db.RegisterMessage(GetTimeRequest)

GetTimeResponse = _reflection.GeneratedProtocolMessageType('GetTimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETTIMERESPONSE,
  '__module__' : 'rtc_pb2'
  # @@protoc_insertion_point(class_scope:firefly.rtc.v1.GetTimeResponse)
  })
_sym_db.RegisterMessage(GetTimeResponse)

SetTimeRequest = _reflection.GeneratedProtocolMessageType('SetTimeRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETTIMEREQUEST,
  '__module__' : 'rtc_pb2'
  # @@protoc_insertion_point(class_scope:firefly.rtc.v1.SetTimeRequest)
  })
_sym_db.RegisterMessage(SetTimeRequest)

SetTimeResponse = _reflection.GeneratedProtocolMessageType('SetTimeResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETTIMERESPONSE,
  '__module__' : 'rtc_pb2'
  # @@protoc_insertion_point(class_scope:firefly.rtc.v1.SetTimeResponse)
  })
_sym_db.RegisterMessage(SetTimeResponse)

Configuration = _reflection.GeneratedProtocolMessageType('Configuration', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGURATION,
  '__module__' : 'rtc_pb2'
  # @@protoc_insertion_point(class_scope:firefly.rtc.v1.Configuration)
  })
_sym_db.RegisterMessage(Configuration)

GetConfigurationRequest = _reflection.GeneratedProtocolMessageType('GetConfigurationRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGURATIONREQUEST,
  '__module__' : 'rtc_pb2'
  # @@protoc_insertion_point(class_scope:firefly.rtc.v1.GetConfigurationRequest)
  })
_sym_db.RegisterMessage(GetConfigurationRequest)

GetConfigurationResponse = _reflection.GeneratedProtocolMessageType('GetConfigurationResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETCONFIGURATIONRESPONSE,
  '__module__' : 'rtc_pb2'
  # @@protoc_insertion_point(class_scope:firefly.rtc.v1.GetConfigurationResponse)
  })
_sym_db.RegisterMessage(GetConfigurationResponse)

SetConfigurationRequest = _reflection.GeneratedProtocolMessageType('SetConfigurationRequest', (_message.Message,), {
  'DESCRIPTOR' : _SETCONFIGURATIONREQUEST,
  '__module__' : 'rtc_pb2'
  # @@protoc_insertion_point(class_scope:firefly.rtc.v1.SetConfigurationRequest)
  })
_sym_db.RegisterMessage(SetConfigurationRequest)

SetConfigurationResponse = _reflection.GeneratedProtocolMessageType('SetConfigurationResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETCONFIGURATIONRESPONSE,
  '__module__' : 'rtc_pb2'
  # @@protoc_insertion_point(class_scope:firefly.rtc.v1.SetConfigurationResponse)
  })
_sym_db.RegisterMessage(SetConfigurationResponse)

_RTC = DESCRIPTOR.services_by_name['RTC']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\220\246\035\n\202\246\035\002fd'
  _RTC._options = None
  _RTC._serialized_options = b'\230\246\035\001'
  _RTC.methods_by_name['getTime']._options = None
  _RTC.methods_by_name['getTime']._serialized_options = b'\240\246\035\001'
  _RTC.methods_by_name['setTime']._options = None
  _RTC.methods_by_name['setTime']._serialized_options = b'\240\246\035\002'
  _RTC.methods_by_name['getConfiguration']._options = None
  _RTC.methods_by_name['getConfiguration']._serialized_options = b'\240\246\035\003'
  _RTC.methods_by_name['setConfiguration']._options = None
  _RTC.methods_by_name['setConfiguration']._serialized_options = b'\240\246\035\004'
  _DISPLAYFORMAT._serialized_start=500
  _DISPLAYFORMAT._serialized_end=555
  _GETTIMEREQUEST._serialized_start=44
  _GETTIMEREQUEST._serialized_end=60
  _GETTIMERESPONSE._serialized_start=62
  _GETTIMERESPONSE._serialized_end=120
  _SETTIMEREQUEST._serialized_start=122
  _SETTIMEREQUEST._serialized_end=163
  _SETTIMERESPONSE._serialized_start=165
  _SETTIMERESPONSE._serialized_end=182
  _CONFIGURATION._serialized_start=184
  _CONFIGURATION._serialized_end=280
  _GETCONFIGURATIONREQUEST._serialized_start=282
  _GETCONFIGURATIONREQUEST._serialized_end=307
  _GETCONFIGURATIONRESPONSE._serialized_start=309
  _GETCONFIGURATIONRESPONSE._serialized_end=389
  _SETCONFIGURATIONREQUEST._serialized_start=391
  _SETCONFIGURATIONREQUEST._serialized_end=470
  _SETCONFIGURATIONRESPONSE._serialized_start=472
  _SETCONFIGURATIONRESPONSE._serialized_end=498
  _RTC._serialized_start=558
  _RTC._serialized_end=951
# @@protoc_insertion_point(module_scope)
